#!/bin/bash

applications=applications/*
# MacOS doesn't include realpath, until Ventura
here=$(realpath $0)

# Add githooks
for p in $applications
do
    if ! test -d "$p/.git"
    then
        continue
    fi

    ln -s -f "$here/prepare-commit-msg" "$p/.git/hooks/prepare-commit-msg"
done

# Add Nix shells
for p in $applications
do
    shell="$here/shells/$(basename $p).nix"

    if test -f $shell
    then
        echo "Installing nix shell in $p"

        # Symbolic link so we can continue editing
        rm -f "$p/shell.nix"
        ln -s -f $shell "$p/shell.nix"
        echo shell.nix >> "$p/.git/info/exclude"
    fi

    # Sometimes there already is a shell.nix in the repo
    if test -n "$(find $p -maxdepth 1 -name '*.nix' -print -quit)"
    then
        echo "Setting up direnv to use the nix shell"

        if test -f flake.nix
        then
            echo use flake > "$p/.envrc"
        else
            echo use nix > "$p/.envrc"
        fi

        cat >> "$p/.git/info/exclude" << EOF
.direnv/
.envrc
EOF
        (cd $p; direnv allow)
    fi

    # Solargraph
    if test "$(basename $p)" == "payroll"
    then
        cp "$here/solargraph.yml" "$p/.solargraph.yml"
        # @todo use direnv layouts instead
        # ```
        # layout php
        # layout ruby
        # layout node
        # ```
        cat >> "$p/.git/info/exclude" << EOF
gemset.nix
.solargraph.yml
EOF
    fi
done
