#!/bin/bash

BASE_PATH="$HOME/humility/applications/"

ANGULAR_PROJECTS=(ui)
LARAVEL_PROJECTS=(hr admin)
RAILS_PROJECTS=(payroll)

applications="$BASE_PATH/*"

# MacOS doesn't include realpath, until Ventura
here=$(dirname "$(readlink -f "$0" )")

# Add githooks
for p in $applications
do
    if ! test -d "$p/.git"
    then
        continue
    fi

    ln -s -f "$here/prepare-commit-msg" "$p/.git/hooks/prepare-commit-msg"
done

# Add Nix shells
for p in $applications
do
    shell="$here/shells/$(basename "$p").nix"

    if test -f "$shell"
    then
        echo "Installing nix shell in $p"

        # Symbolic link so we can continue editing
        rm -f "$p/shell.nix"
        ln -s -f "$shell" "$p/shell.nix"
        echo shell.nix >> "$p/.git/info/exclude"
    fi

    # Sometimes there already is a shell.nix in the repo
    if test -n "$(find "$p" -maxdepth 1 -name '*.nix' -print -quit)"
    then
        echo "Setting up direnv to use the nix shell"

        if test -f flake.nix
        then
            echo use flake > "$p/.envrc"
        else
            echo use nix > "$p/.envrc"
        fi

        cat >> "$p/.git/info/exclude" << EOF
.direnv/
.envrc
EOF
        direnv allow "$p" 
    fi
done

# Set up Laravel projects
for project in "${LARAVEL_PROJECTS[@]}"
do
    p="$BASE_PATH/$project"

    echo layout php >> "$p/.envrc"

    echo "Creating Psalm config file"
    direnv exec "$p" psalm --init
    echo "psalm.xml" >> "$p/.git/info/exclude"
done

# Set up Angular projects
for project in "${ANGULAR_PROJECTS[@]}"
do
    p="$BASE_PATH/$project"

    echo layout node >> "$p/.envrc"
    direnv exec "$p" npm ci
    direnv exec "$p" npm install --no-save @angular/language-server
done

for project in "${RAILS_PROJECTS[@]}"
do
    p="$BASE_PATH/$project"

    # This will cause gems to be installed in the .direnv directory
    echo 'layout ruby' >> "$p/.envrc"

    ln -s -f "$here/rails/solargraph.yml" "$p/.solargraph.yml"
    ln -s -f "$here/rails/solargraph-setup.sh" "$p/"

    cat >> "$p/.git/info/exclude" << EOF
.solargraph.yml
app/rails.rb
solargraph-setup.sh
EOF

    # Install gems and set up Solargraph
    "$p/solargraph-setup.sh"
done
